[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
